name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # 每次你点推送代码到 main 分支，就会自动触发更新

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "dist/*"
          target: "/var/www/html/dist"  # 这里确保是你服务器上放网页的文件夹
          strip_components: 1
